//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOLETA()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal NUMEROBOLETA { get; set; }
        public System.DateTime FECHABOLETA { get; set; }
        public int VALORBOLETA { get; set; }
        public decimal USUARIO_USUARIOID { get; set; }
        public decimal MEDIO_PAGO_MEDIOPAGOID { get; set; }
        public decimal CLIENTE_RUNCLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MEDIO_PAGO MEDIO_PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
