
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class CLIENTE
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CLIENTE()
    {

        this.BOLETA = new HashSet<BOLETA>();

    }


    public decimal RUNCLIENTE { get; set; }

    public string DV { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO { get; set; }

    public System.DateTime FECHANACIMIENTO { get; set; }

    public string DIRECCION { get; set; }

    public int TELEFONO { get; set; }

    public decimal ESTADO_FIADO_IDESTADO { get; set; }

    public decimal TIPO_CLIENTE_IDTIPO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BOLETA> BOLETA { get; set; }

    public virtual ESTADO_FIADO ESTADO_FIADO { get; set; }

    public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }

}

}
