
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class DJANGO_CONTENT_TYPE
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DJANGO_CONTENT_TYPE()
    {

        this.AUTH_PERMISSION = new HashSet<AUTH_PERMISSION>();

        this.DJANGO_ADMIN_LOG = new HashSet<DJANGO_ADMIN_LOG>();

    }


    public long ID { get; set; }

    public string APP_LABEL { get; set; }

    public string MODEL { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AUTH_PERMISSION> AUTH_PERMISSION { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DJANGO_ADMIN_LOG> DJANGO_ADMIN_LOG { get; set; }

}

}
