
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class ORDEN_PEDIDO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ORDEN_PEDIDO()
    {

        this.DETALLE_PEDIDO = new HashSet<DETALLE_PEDIDO>();

    }


    public decimal NUMEROORDEN { get; set; }

    public System.DateTime FECHACREACION { get; set; }

    public decimal TOTAL { get; set; }

    public System.DateTime FECHARECEPCION { get; set; }

    public decimal PROVEEDOR_RUT { get; set; }

    public decimal ESTADO_ORDEN_IDESTADO { get; set; }

    public decimal USUARIO_RUNUSUARIO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }

    public virtual ESTADO_ORDEN ESTADO_ORDEN { get; set; }

    public virtual PROVEEDOR PROVEEDOR { get; set; }

    public virtual USUARIO USUARIO { get; set; }

}

}
