//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_PEDIDO()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal NUMERORDEN { get; set; }
        public System.DateTime FECHAORDEN { get; set; }
        public int VALORORDEN { get; set; }
        public Nullable<System.DateTime> FECHARECEPCION { get; set; }
        public decimal PROVEEDOR_RUTPROVEEDOR { get; set; }
        public decimal ESTADO_ORDEN_ESTADOID { get; set; }
        public decimal USUARIO_RUNUSUARIO { get; set; }
    
        public virtual ESTADO_ORDEN ESTADO_ORDEN { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
