
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class V_BOLETAS
{

    public decimal NUMERO { get; set; }

    public System.DateTime FECHA_CREACION { get; set; }

    public decimal TOTAL { get; set; }

    public decimal IDMEDIOPAGO { get; set; }

    public string MEDIO_PAGO { get; set; }

    public decimal RUN_CLIENTE { get; set; }

    public string NOMBRE_CLIENTE { get; set; }

    public decimal RUN_USUARIO { get; set; }

    public string NOMBRE_VENDEDOR { get; set; }

    public decimal IDESTADO { get; set; }

    public string DESCRIPCION { get; set; }

}

}
