//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CLIENTES_EFECTIVO
    {
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public decimal TOTAL { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
