
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class V_CLIENTES
{

    public decimal RUN { get; set; }

    public string DV { get; set; }

    public string NOMBRE_CLIENTE { get; set; }

    public System.DateTime FECHANACIMIENTO { get; set; }

    public string DIRECCION { get; set; }

    public int TELEFONO { get; set; }

    public decimal IDTIPO { get; set; }

    public string TIPO_CLIENTE { get; set; }

    public decimal IDESTADO { get; set; }

    public string ESTADO_FIADO { get; set; }

}

}
