//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CLIENTES
    {
        public decimal RUNCLIENTE { get; set; }
        public string DVCLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public System.DateTime FECHANACIMIENTO { get; set; }
        public string DIRECCIONCLIENTE { get; set; }
        public int TELEFONOCLIENTE { get; set; }
        public string DESCRIPCLIENTE { get; set; }
        public string DESCRIPESTADO { get; set; }
    }
}
