
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class V_DETALLE_ORDEN
{

    public decimal IDDETALLEO { get; set; }

    public decimal ORDEN_PEDIDO_NUMEROORDEN { get; set; }

    public string PRODUCTO_CODIGO { get; set; }

    public string NOMBRE { get; set; }

    public decimal CANTIDAD { get; set; }

    public Nullable<decimal> TOTAL { get; set; }

}

}
