//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCTOS
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public decimal PRECIO_COMPRA { get; set; }
        public decimal STOCK { get; set; }
        public decimal STOCK_CRITICO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public decimal IDCATEGORIA { get; set; }
        public string CATEGORIA { get; set; }
    }
}
