//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PROVEEDORES
    {
        public decimal RUT { get; set; }
        public string DV { get; set; }
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public int TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public decimal RUBROID { get; set; }
        public string RUBRO { get; set; }
    }
}
