//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USUARIOS
    {
        public string RUN_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public System.DateTime FECHANACIMIENTO { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public decimal IDTIPO { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
