//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USUARIOS
    {
        public decimal RUNUSUARIO { get; set; }
        public string DVUSUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CLAVEUSUARIO { get; set; }
        public System.DateTime FECHANACIMIENTO { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public string DIRECCIONUSUARIO { get; set; }
        public decimal TELEFONOUSUARIO { get; set; }
        public string DESCRIPUSUARIO { get; set; }
    }
}
